/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AConv;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel L
 */
public class ConvertidorTemp extends javax.swing.JPanel {

    /**
     * Creates new form TempConvertidor
     */
    double valor;
    public ConvertidorTemp() {
        initComponents();
        ConvertidorTemp.this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new AConv.PanelRound();
        Conteiner = new AConv.PanelRound();
        BGPIn = new AConv.PanelRound();
        TextIn = new javax.swing.JTextField();
        BGPOut = new AConv.PanelRound();
        TextOut = new javax.swing.JTextField();
        botonConvertir = new AConv.PanelRound();
        Cleanbtn = new AConv.PanelRound();
        panelRound2 = new AConv.PanelRound();
        List1 = new javax.swing.JComboBox<>();
        panelRound5 = new AConv.PanelRound();
        List2 = new javax.swing.JComboBox<>();

        BG.setBackground(new java.awt.Color(51, 51, 51));
        BG.setPreferredSize(new java.awt.Dimension(900, 700));
        BG.setRoundBottomRight(40);
        BG.setRoundTopRight(40);

        Conteiner.setBackground(new java.awt.Color(255, 255, 255));
        Conteiner.setPreferredSize(new java.awt.Dimension(410, 578));
        Conteiner.setRoundBottomLeft(10);
        Conteiner.setRoundBottomRight(10);
        Conteiner.setRoundTopLeft(10);
        Conteiner.setRoundTopRight(10);

        BGPIn.setBackground(new java.awt.Color(102, 102, 102));
        BGPIn.setRoundBottomLeft(20);
        BGPIn.setRoundBottomRight(20);
        BGPIn.setRoundTopLeft(20);
        BGPIn.setRoundTopRight(20);

        TextIn.setBackground(new java.awt.Color(102, 102, 102));
        TextIn.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TextIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextIn.setBorder(null);
        TextIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGPInLayout = new javax.swing.GroupLayout(BGPIn);
        BGPIn.setLayout(BGPInLayout);
        BGPInLayout.setHorizontalGroup(
            BGPInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextIn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        BGPInLayout.setVerticalGroup(
            BGPInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextIn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        BGPOut.setBackground(new java.awt.Color(102, 102, 102));
        BGPOut.setRoundBottomLeft(20);
        BGPOut.setRoundBottomRight(20);
        BGPOut.setRoundTopLeft(20);
        BGPOut.setRoundTopRight(20);

        TextOut.setBackground(new java.awt.Color(102, 102, 102));
        TextOut.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TextOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextOut.setBorder(null);
        TextOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGPOutLayout = new javax.swing.GroupLayout(BGPOut);
        BGPOut.setLayout(BGPOutLayout);
        BGPOutLayout.setHorizontalGroup(
            BGPOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextOut)
                .addContainerGap())
        );
        BGPOutLayout.setVerticalGroup(
            BGPOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextOut, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonConvertir.setBackground(new java.awt.Color(102, 102, 102));
        botonConvertir.setRoundBottomLeft(40);
        botonConvertir.setRoundBottomRight(40);
        botonConvertir.setRoundTopLeft(40);
        botonConvertir.setRoundTopRight(40);
        botonConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonConvertirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout botonConvertirLayout = new javax.swing.GroupLayout(botonConvertir);
        botonConvertir.setLayout(botonConvertirLayout);
        botonConvertirLayout.setHorizontalGroup(
            botonConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        botonConvertirLayout.setVerticalGroup(
            botonConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Cleanbtn.setBackground(new java.awt.Color(51, 51, 51));
        Cleanbtn.setRoundBottomLeft(40);
        Cleanbtn.setRoundBottomRight(40);
        Cleanbtn.setRoundTopLeft(40);
        Cleanbtn.setRoundTopRight(40);
        Cleanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CleanbtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CleanbtnLayout = new javax.swing.GroupLayout(Cleanbtn);
        Cleanbtn.setLayout(CleanbtnLayout);
        CleanbtnLayout.setHorizontalGroup(
            CleanbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        CleanbtnLayout.setVerticalGroup(
            CleanbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound2.setBackground(new java.awt.Color(51, 51, 51));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        List1.setBackground(new java.awt.Color(51, 51, 51));
        List1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        List1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin", "Rankie" }));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 122, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelRound5.setBackground(new java.awt.Color(51, 51, 51));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        List2.setBackground(new java.awt.Color(51, 51, 51));
        List2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        List2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin", "Rankie" }));

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(List2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ConteinerLayout = new javax.swing.GroupLayout(Conteiner);
        Conteiner.setLayout(ConteinerLayout);
        ConteinerLayout.setHorizontalGroup(
            ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConteinerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BGPOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BGPIn, javax.swing.GroupLayout.PREFERRED_SIZE, 363, Short.MAX_VALUE)
                    .addGroup(ConteinerLayout.createSequentialGroup()
                        .addGroup(ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonConvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cleanbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        ConteinerLayout.setVerticalGroup(
            ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConteinerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BGPIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cleanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BGPOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(Conteiner, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Conteiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextOutActionPerformed

    private void TextInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextInActionPerformed

    private void botonConvertirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConvertirMousePressed
    String valorTexto = TextIn.getText();
    double valor;
    
    try {
    if (valorTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor");
       return;
    } 
    valor = Double.parseDouble(valorTexto);
    } catch (NumberFormatException Letras) {   
    JOptionPane.showMessageDialog(null, "Por favor, unicamente utilice numeros");
    return;
    }   
    
    String Origen = (String) List1.getSelectedItem();
    String Destino = (String) List2.getSelectedItem();
    
    if (Origen.equals(Destino)) {
    JOptionPane.showMessageDialog(null, "Las monedas a convertir tiene que ser distintas");
    }

    if (List1.getSelectedIndex() == -1) {
        List1.addItem("Celsius");
        List1.addItem("Fahrenheit");
        List1.addItem("Kelvin");
        List1.addItem("Rankie");
    }
    if (List2.getSelectedIndex() == -1) {
        List2.addItem("Celsius");
        List2.addItem("Fahrenheit");
        List2.addItem("Kelvin");
        List2.addItem("Rankie");
    }

double resultado = 0.0;

if (Origen.equals("Celsius") && Destino.equals("Fahrenheit")) {
    resultado = (valor * 9/5) + 32;
} else if (Origen.equals("Fahrenheit") && Destino.equals("Celsius")) {
    resultado = (valor - 32) * 5/9;
}
else if (Origen.equals("Celsius") && Destino.equals("Kelvin")) {
    resultado = valor + 273.15;
} else if (Origen.equals("Kelvin") && Destino.equals("Celsius")) {
    resultado = valor - 273.15;
}
else if (Origen.equals("Celsius") && Destino.equals("Rankine")) {
    resultado = (valor + 273.15) * 9/5;
} else if (Origen.equals("Rankine") && Destino.equals("Celsius")) {
    resultado = (valor - 491.67) * 5/9;
}
else if (Origen.equals("Fahrenheit") && Destino.equals("Kelvin")) {
    resultado = (valor + 459.67) * 5/9;
} else if (Origen.equals("Kelvin") && Destino.equals("Fahrenheit")) {
    resultado = (valor * 9/5) - 459.67;
}
else if (Origen.equals("Fahrenheit") && Destino.equals("Rankine")) {
    resultado = valor + 459.67;
} else if (Origen.equals("Rankine") && Destino.equals("Fahrenheit")) {
    resultado = valor - 459.67;
}
else if (Origen.equals("Kelvin") && Destino.equals("Rankine")) {
    resultado = valor * 9/5;
} else if (Origen.equals("Rankine") && Destino.equals("Kelvin")) {
    resultado = valor * 5/9;
}

   
    TextOut.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botonConvertirMousePressed

    private void CleanbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CleanbtnMousePressed
        TextIn.setText(null);
        TextOut.setText(null);
        
    }//GEN-LAST:event_CleanbtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AConv.PanelRound BG;
    private AConv.PanelRound BGPIn;
    private AConv.PanelRound BGPOut;
    private AConv.PanelRound Cleanbtn;
    private AConv.PanelRound Conteiner;
    private javax.swing.JComboBox<String> List1;
    private javax.swing.JComboBox<String> List2;
    private javax.swing.JTextField TextIn;
    private javax.swing.JTextField TextOut;
    private AConv.PanelRound botonConvertir;
    private AConv.PanelRound panelRound2;
    private AConv.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
